# Generated by Django 2.0.2 on 2018-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
