# Generated by Django 2.0.2 on 2018-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_event_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hide',
        ),
        migrations.AddField(
            model_name='event',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
