# Generated by Django 2.0.2 on 2018-03-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180311_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='display',
        ),
    ]
