# Generated by Django 2.0.2 on 2018-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_event_display_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_display_format',
            field=models.CharField(choices=[('single date', 'single date'), ('date range', 'date range')], default='single date', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='time_display_format',
            field=models.CharField(choices=[('start time only', 'start time only'), ('time range', 'time range'), ('no time', 'no time')], default='start time only', max_length=20),
        ),
    ]
