# Generated by Django 2.1.2 on 2018-10-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image_file',
        ),
    ]
