# Generated by Django 2.1.2 on 2018-10-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181017_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_file',
            new_name='image',
        ),
    ]
