# Generated by Django 2.0.2 on 2018-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180312_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='officer_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
