# Generated by Django 2.0.2 on 2018-03-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_member_officer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='officer_position',
            field=models.CharField(blank=True, choices=[(1, 'President'), (2, 'Vice President'), (3, 'Team Captain'), (4, 'Treasurer'), (5, 'PR Chair'), (6, 'Fundraising Chair')], max_length=20, null=True),
        ),
    ]
