# Generated by Django 2.1.2 on 2018-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20180312_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='officer_position',
            field=models.IntegerField(blank=True, choices=[(1, 'President'), (2, 'Vice President'), (3, 'Team Captain'), (4, 'Treasurer'), (5, 'PR Chair'), (6, 'Fundraising Chair')], null=True),
        ),
    ]
