# Generated by Django 2.1.2 on 2018-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20181011_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('Rec', 'Rec'), ('Comp', 'Comp')], max_length=20, null=True),
        ),
    ]
