# Generated by Django 2.1.2 on 2018-10-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20181012_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
    ]
