# Generated by Django 2.1.2 on 2018-10-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='insta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
