# Generated by Django 2.1.2 on 2018-10-22 03:53

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20181012_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
